#ifndef _CONFIGLIGHTNING_H
#define _CONFIGLIGHTNING_H

//#define LIGHTNING_I386
//#define LIGHTNING_X86_64
#define LIGHTNING_ARM
//#define LIGHTNING_MIPS
//#define LIGHTNING_MIPS64
//#define LIGHTNING_PPC
//#define LIGHTNING_SPARC

#define __WORDSIZE 32
//#define __WORDSIZE 64

#endif
