#ifndef _CONFIGTCC_H
#define _CONFIGTCC_H

/* Automatically generated by configure - do not modify */
#ifndef CONFIG_TCCDIR
# define CONFIG_TCCDIR "./"
#endif
#define TCC_TARGET_ARM
#define TCC_ARM_EABI
#define TCC_IS_NATIVE
#define ONE_SOURCE
#define GCC_MAJOR 4
#define HOST_ARM 1
#define TCC_ARM_VERSION 5
#define TCC_VERSION "0.9.25"

#endif
