#ifndef _CONFIGTCC_H
#define _CONFIGTCC_H

/* Automatically generated by configure - do not modify */
#ifndef CONFIG_TCCDIR
# define CONFIG_TCCDIR "C:/Program Files/tcc"
#endif
#define TCC_TARGET_I386
#define TCC_TARGET_PE
#define ONE_SOURCE
#define GCC_MAJOR 4
#define HOST_I386 1
#define CONFIG_WIN32 1
#define TCC_VERSION "0.9.25"

#endif
